package com.campus.client.rag;

import java.util.List;

/**
 * Stores the result returned from the RAG process
 * It contains the generated answer, the context used, and the source names
 */
public class RagResponse {

    /**Answer generated by the LLM*/
    private final String answer;

    /** Context passages retrieved via search_campus_info (the campus knowledge base) */
    private final String contextUsed;

    /** Source names extracted from the retrieved context */
    private final List<String> sources;

    /**
     * Creates a RAG response object
     *
     * @param answer      answer generated by the LLM
     * @param contextUsed retrieved context string from search_campus_info used to generate answer
     * @param sources    source names from the retrieved context
     */
    public RagResponse(String answer, String contextUsed, List<String> sources) {
        this.answer = answer;
        this.contextUsed = contextUsed;
        this.sources = sources;
    }

    public String getAnswer() {
        return answer;
    }

    public String getContextUsed() {
        return contextUsed;
    }

    public List<String> getSources() {
        return sources;
    }

    @Override
    public String toString() {
        return "RagResponse{answer='" + answer + "', contextLength=" + contextUsed.length()
                + ", sources=" + sources + "}";
    }
}
